export const listProject = [
  {
    id:0,
    link:"https://konflix-arsatteguh.vercel.app",
    hash:"LTEyVyRj?bRkWVV@kDoL~qt7WqRj",
    url: "/project1.png",
    title: "Redesign Netflix",
    desc: "Netflix Redesign is a layout mastering project that integrates with the MovieDB API using React Js, CSS, Bootsrap, and Axios. You can also see the latest Movies, most popular Movies, search for Movies and see details of Movies.",
  },
  {
    id:1,
    link:"",
    hash:"LUM%[+00t7~qIUofxvt7xu%2t7j[",
    url: "/project2.png",
    title: "Landing Page SPA",
    desc: "Landing Page (Single Page Application) is a project for one of the Software House companies in Surabaya which uses Next Js, TypeScript, Nodemailer, Next-i18, Next-Theme. Allows visitors to change the dark theme on the website, send emails to companies and use multi international languages.",
  },
  {
    id:2,
    link:"https://47.237.28.68",
    hash:"LaMaL#og_2jXM|ogxtM{~poJIURk",
    url: "/project3.png",
    title: "Rest Full API - NEST JS",
    desc: "a Restful API Building using Nest Js, Typescript, MongoDB, Postgresql, and Prisma technology and has been deployed on ALIBABA CLOUD",
  },
  {
    id:3,
    link:"https://invoice-generator-git-main-arsatteguh.vercel.app",
    hash:"LDQJcdD%~p%M4n4n?b-;4nD%of%M",
    url: "/product_invoice.png",
    title: "Invoce Generator",
    desc: "Invoice Generator is a project for entrepreneurs who want speed in creating PDF invoices. Using Next Js, Tailwind css, Next-Theme, Nodemailer, MongoDB. Allows users to save downloaded invoices to a database and send them to email. They can also view all invoice lists, view invoice status, total invoice amount, and can resend invoices to the intended email.",
  },
  {
    id:4,
    link:"https://arsat-test-slicing.vercel.app",
    hash:"LDQJcdD%~p%M4n4n?b-;4nD%of%M",
    url: "/slicing1.png",
    title: "Slicing on based Figma",
    desc: "Slicing based on Figma, using next js 14, Tailwind css, Typescript produces a professional and responsive appearance.",
  },
  {
    id:5,
    link:"https://learn-management-system-one.vercel.app",
    hash:"LDQJcdD%~p%M4n4n?b-;4nD%of%M",
    url: "/lms.png",
    title: "Learn Management System",
    desc: "The Learn Management System was created using Fullstack Next Js, Typescript, node Js, mongoDB, Pusher-Js and others. The Payment Gateway features Comment Like and Dislike chapters in real time, and Multi Role.",
  },
];
